### ISSUE TITLE
build.sh doesn't support multidigit minor versions

### ISSUE THREAD

**Issue by krystian-hebel** [pcengines/pce-fw-builder#27]
Version 4.10 is considered as a legacy version by this script, which leads to build failure.

**Comment by pietrushnic** [comment]
Regexp in this function have to be changed: https://github.com/pcengines/pce-fw-builder/blob/master/build.sh#L3

@miczyg1 who can do that? Maybe Łukasz W. or Piotr?

**Comment by miczyg1** [comment]
@artur-rs could You handle that in Your team?

**Comment by krystian-hebel** [comment]
Change added in commit `a40d698d87a50c5f98aab0662644036a40af66c4` breaks check for older versions, e.g. `4.4` is being recognized by `4.[1-9][0-9]*)`

**Comment by pietrushnic** [comment]
@artur-rs ?

**Comment by miczyg1** [comment]
https://github.com/pcengines/pce-fw-builder/pull/30
